version: 2

references:
  ## Workspaces
  workspace: &workspace ~/src

  ## Docker image configurations
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb
      _JAVA_OPTIONS:
        '-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap'
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

  ## Cache
  gradle_key:
    &gradle_key jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

  gems_key: &gems_key gems-{{ checksum "Gemfile.lock" }}

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: *gradle_key

  restore_gems_cache: &restore_gems_cache
    restore_cache:
      key: *gems_key

  save_gradle_cache: &save_gradle_cache
    save_cache:
      key: *gradle_key
      paths:
        - ~/.gradle
        - ~/.m2

  save_gems_cache: &save_gems_cache
    save_cache:
      key: *gems_key
      paths:
        - vendor/bundle

  ## Dependencies
  ruby_dependencies: &ruby_dependencies
    run:
      name: Download Ruby Dependencies
      command: bundle check || bundle install --path vendor/bundle

  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

  ## Git Config
  set_git_config: &set_git_config
    run:
      name: Set Git user
      command:
        git config --global user.email "ulhas.sm@gmail.com" && git config --global user.name "Ulhas Mandrawadkar"

jobs:
  ## Deploy Staging to Crashlytics Beta
  deploy_staging:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *restore_gems_cache
      - *ruby_dependencies
      - *android_dependencies
      - *save_gradle_cache
      - *save_gems_cache
      - *set_git_config
      - run:
          name: Deploy Staging to Crashlytics Beta
          command: bundle exec fastlane staging_beta

  ## Deploy Preprod to Crashlytics Beta
  deploy_preprod:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *restore_gems_cache
      - *ruby_dependencies
      - *android_dependencies
      - *save_gradle_cache
      - *save_gems_cache
      - *set_git_config
      - run:
          name: Deploy Preprod to Crashlytics Beta
          command: bundle exec fastlane preprod_beta

workflows:
  version: 2
  workflow:
    jobs:
      - deploy_staging:
          filters:
            branches:
              only:
                - develop
      - deploy_preprod:
          filters:
            branches:
              only:
                - preprod
